import pages from './site-index.generated.json';

// Generated by scripts/gen-site-index.mjs on prebuild/predev — never edit the
// JSON by hand. Every public page of the site, sorted by path.
export interface SitePage {
  path: string;
  title: string;
  description?: string;
}

export const SITE_URL = 'https://eela.empowrcic.org';
export const SITE_PAGES: SitePage[] = pages;
